# path: .github/workflows/build.yml
name: Build Disks
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up tools (cc65 + Python + Java 21)
        run: |
          sudo apt-get update
          sudo apt-get install -y cc65 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install Pillow
          # Download AppleCommander CLI (pinned)
          AC_VERSION=1.11.0
          curl -L "https://github.com/AppleCommander/AppleCommander/releases/download/${AC_VERSION}/AppleCommander-ac-${AC_VERSION}.jar" -o ac.jar
          # sanity check the jar
          java -version
          java -jar ac.jar -help | head -n 2 || true

      - name: Prepare folders
        run: |
          mkdir -p build src tools assets cfg

      - name: Create fallback title.png if missing
        run: |
          if [ ! -f assets/title.png ]; then
            python3 - << 'PY'
from PIL import Image, ImageDraw
img = Image.new('L', (280,192), 255)
d = ImageDraw.Draw(img)
d.text((40,80), "SEAN'S GARAGE", fill=0)
d.text((80,110), "GIVEAWAY", fill=0)
img.save('assets/title.png')
PY
          fi

      - name: Assemble with ca65 + ld65
        run: |
          # assemble to object
          ca65 -t none -o build/game.o src/seans_garage_giveaway.s
          # link to raw BIN at $0800 using our linker cfg
          ld65 -C cfg/apple2bin.cfg -o build/SEANSGAME.bin build/game.o
          # convert PNG -> HGR
          python3 tools/png2hgr.py assets/title.png build/TITLE.hgr
          # make DOS 3.3 bootable .dsk
          java -jar ac.jar -dos140 build/SeanGarage.dsk SEANSGAR
          java -jar ac.jar -p build/SeanGarage.dsk HELLO BAS < assets/HELLO.bas
          java -jar ac.jar -p build/SeanGarage.dsk SEANSGAME BIN 0x0800 < build/SEANSGAME.bin
          java -jar ac.jar -p build/SeanGarage.dsk TITLE BIN 0x2000 < build/TITLE.hgr
          # optional ProDOS .po if you uploaded assets/NewDisk.po
          if [ -f assets/NewDisk.po ]; then
            cp assets/NewDisk.po build/SeanGarage.po
            java -jar ac.jar -p build/SeanGarage.po STARTUP BAS < assets/STARTUP.bas
            java -jar ac.jar -p build/SeanGarage.po SEANSGAME BIN 0x0800 < build/SEANSGAME.bin
            java -jar ac.jar -p build/SeanGarage.po TITLE BIN 0x2000 < build/TITLE.hgr
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: disks
          path: build/*.{dsk,po}
